In [1]:
import os
# print(os.listdir('./metrics'))

import numpy as np
import pandas as pd
"""
./metrics/model_4_AR_NO_SMOOTHING.xlsx
./metrics/model_5_AR_NO_SMOOTHING.xlsx
./metrics/model_6_AR_NO_SMOOTHING.xlsx
"""
model_7 = './metrics/model_7_AR_LE_NO_SMOOTHING.xlsx'
model_8 = './metrics/model_8_AR_LE_NO_SMOOTHING.xlsx'
model_9 = './metrics/model_9_AR_LE_NO_SMOOTHING.xlsx'
models_metrics = [os.path.join('metrics', path) for path in os.listdir('./metrics/') if '~' not in path]
models_metrics


['metrics\\model_10_AR_GSZ_NO_SMOOTHING.xlsx',
 'metrics\\model_10_AR_GSZ_SMOOTHING_15_21.xlsx',
 'metrics\\model_10_AR_GSZ_SMOOTHING_8_12.xlsx',
 'metrics\\model_10_AR_LE_NO_SMOOTHING.xlsx',
 'metrics\\model_10_AR_LE_SMOOTHING_15_21.xlsx',
 'metrics\\model_10_AR_LE_SMOOTHING_8_12.xlsx',
 'metrics\\model_10_AR_NO_SMOOTHING.xlsx',
 'metrics\\model_10_AR_SMOOTHING_15_21.xlsx',
 'metrics\\model_10_AR_SMOOTHING_8_12.xlsx',
 'metrics\\model_11_AR_GSZ_NO_SMOOTHING.xlsx',
 'metrics\\model_11_AR_GSZ_SMOOTHING_15_21.xlsx',
 'metrics\\model_11_AR_GSZ_SMOOTHING_8_12.xlsx',
 'metrics\\model_11_AR_LE_NO_SMOOTHING.xlsx',
 'metrics\\model_11_AR_LE_SMOOTHING_15_21.xlsx',
 'metrics\\model_11_AR_LE_SMOOTHING_8_12.xlsx',
 'metrics\\model_11_AR_NO_SMOOTHING.xlsx',
 'metrics\\model_11_AR_SMOOTHING_15_21.xlsx',
 'metrics\\model_11_AR_SMOOTHING_8_12.xlsx',
 'metrics\\model_1_AR_GSZ_NO_SMOOTHING.xlsx',
 'metrics\\model_1_AR_GSZ_SMOOTHING_15_21.xlsx',
 'metrics\\model_1_AR_GSZ_SMOOTHING_8_12.xlsx',
 'metrics\\

In [14]:
 # Load data 
# m7 = pd.read_excel(model_7, sheet_name=None)
# m8 = pd.read_excel(model_8, sheet_name=None)
# m9 = pd.read_excel(model_9, sheet_name=None)
from natsort import natsorted, ns
models_metrics = natsorted(models_metrics, alg=ns.IGNORECASE)
# models_metrics

previous_num = '0'
for metrics in models_metrics:
    postfix = metrics[metrics.find('_') + 1:-5]
    model_number = postfix[:postfix.find('_')]
    # print(model_number)
    postfix = postfix[postfix.find('_') + 1:].replace('_', ' ')
    # print(metrics[metrics[metrics.find('_'):].find('_'):].replace('_', ' '), end=', ')
    if previous_num != model_number:
        print('\multirow{9}{*}{' + model_number + '}', end=' & ')
        previous_num = model_number
    else:
        print(' ', end=' & ')

    print(postfix, end=' & ')
    print((pd.read_excel(metrics, sheet_name='all')['Sensitivity'][1] * 100).round(3), end=' & ')
    print((pd.read_excel(metrics, sheet_name='all')[ 'Specificity'][1] * 100).round(3), end=' & ')
    print((pd.read_excel(metrics, sheet_name='all')['F1 score'][1] * 100).round(3), end=' & ')
    print((pd.read_excel(metrics, sheet_name='all')['Sensitivity'][0] * 100).round(3), end=' & ')
    print((pd.read_excel(metrics, sheet_name='all')[ 'Specificity'][0] * 100).round(3), end=' & ')
    print((pd.read_excel(metrics, sheet_name='all')['F1 score'][0] * 100).round(3), end='\\\\\n')
    # break
# print(pd.read_excel(models_metrics[0], sheet_name='all')['F1 score'])
# print(pd.read_excel(models_metrics[0], sheet_name='all')['F1 score'][1])
# print(models_metrics[0])

# print(pd.read_excel(metrics, sheet_name='all')['F1 score'])

\multirow{9}{*}{1} & AR GSZ NO SMOOTHING & 37.709 & 96.741 & 32.622 & 98.567 & 98.236 & 66.94\\
  & AR GSZ SMOOTHING 8 12 & 36.326 & 97.03 & 32.794 & 98.602 & 98.378 & 68.763\\
  & AR GSZ SMOOTHING 15 21 & 35.88 & 97.08 & 32.671 & 98.581 & 98.39 & 68.91\\
  & AR LE NO SMOOTHING & 21.299 & 96.594 & 27.764 & 43.479 & 97.792 & 48.518\\
  & AR LE SMOOTHING 8 12 & 20.484 & 96.868 & 27.306 & 43.388 & 97.959 & 49.185\\
  & AR LE SMOOTHING 15 21 & 20.267 & 96.914 & 27.136 & 43.345 & 97.982 & 49.249\\
  & AR NO SMOOTHING & 21.022 & 96.791 & 27.534 & 42.608 & 98.037 & 47.832\\
  & AR SMOOTHING 8 12 & 20.265 & 97.066 & 27.159 & 42.399 & 98.177 & 48.343\\
  & AR SMOOTHING 15 21 & 20.116 & 97.12 & 27.084 & 42.374 & 98.191 & 48.391\\
\multirow{9}{*}{2} & AR GSZ NO SMOOTHING & 33.576 & 94.439 & 22.91 & 96.164 & 95.55 & 43.902\\
  & AR GSZ SMOOTHING 8 12 & 32.855 & 95.06 & 23.931 & 96.31 & 96.128 & 47.345\\
  & AR GSZ SMOOTHING 15 21 & 32.543 & 95.171 & 24.009 & 96.303 & 96.184 & 47.702\\
  & AR LE NO

In [2]:
m7 = pd.read_excel(model_7, sheet_name=None)
m8 = pd.read_excel(model_8, sheet_name=None)
m9 = pd.read_excel(model_9, sheet_name=None)

In [ ]:
print(m7['labels_dev'].head(3))
# print(m8['labels_dev'].head())
# print(m9['labels_dev'].head())

In [3]:
# m7['labels_dev']['Unnamed: 2837'].dropna()
# Extract the columns names
dev_col = m7['labels_dev'].columns
train_col = m7['labels_train'].columns

# print(len(train_col))
# m7['labels_dev'][col[5]].dropna()[1:]
# m7['labels_dev'][col[-1]].dropna()[1:]
# (len(col) - 1) / 3 - 1
# 2 + 3 * 945
# m7['labels_dev'][col[2837]].dropna()

# Extract the indexes
dev_indexes_pred = [2 + 3 * index for index in range((len(dev_col) - 1) // 3)]
dev_indexes_true = [1 + 3 * index for index in range((len(dev_col) - 1) // 3)]
# col[indexes_pred]
train_indexes_pred = [2 + 3 * index for index in range((len(train_col) - 1) // 3)]
train_indexes_true = [1 + 3 * index for index in range((len(train_col) - 1) // 3)]

# Extract the time series
dev_7 = np.array(m7['labels_dev'][dev_col[dev_indexes_pred]][2:].unstack().dropna(), dtype=np.int8)
dev_8 = np.array(m8['labels_dev'][dev_col[dev_indexes_pred]][2:].unstack().dropna(), dtype=np.int8)
dev_9 = np.array(m9['labels_dev'][dev_col[dev_indexes_pred]][2:].unstack().dropna(), dtype=np.int8)
dev_t_7 = np.array(m7['labels_dev'][dev_col[dev_indexes_true]][2:].unstack().dropna(), dtype=np.int8)
dev_t_8 = np.array(m8['labels_dev'][dev_col[dev_indexes_true]][2:].unstack().dropna(), dtype=np.int8)
dev_t_9 = np.array(m9['labels_dev'][dev_col[dev_indexes_true]][2:].unstack().dropna(), dtype=np.int8)

train_7 = np.array(m7['labels_train'][train_col[train_indexes_pred]][2:].unstack().dropna(), dtype=np.int8)
train_8 = np.array(m8['labels_train'][train_col[train_indexes_pred]][2:].unstack().dropna(), dtype=np.int8)
train_9 = np.array(m9['labels_train'][train_col[train_indexes_pred]][2:].unstack().dropna(), dtype=np.int8)
train_t_7 = np.array(m7['labels_train'][train_col[train_indexes_true]][2:].unstack().dropna(), dtype=np.int8)
train_t_8 = np.array(m8['labels_train'][train_col[train_indexes_true]][2:].unstack().dropna(), dtype=np.int8)
train_t_9 = np.array(m9['labels_train'][train_col[train_indexes_true]][2:].unstack().dropna(), dtype=np.int8)

# m7['labels_dev'][col[indexes_true]][2:].unstack().dropna() or m9['labels_dev'][col[indexes_true]][2:].unstack().dropna()

In [6]:
np.array(m7['labels_dev'][dev_col[dev_indexes_true]][2:].unstack().dropna(), dtype=np.int8).sum() # [2:]

56185

In [4]:
# Define the metric function
from sklearn.metrics import confusion_matrix

def compute_metrics(y_pred, y_true):
    """Compute the metrics of interest.

    Based on https://en.wikipedia.org/wiki/Receiver_operating_characteristic.

    Args:
        y_pred: an array like binary predictions.
        y_true: an array like binary true values.

    Returns:
        A dictionary containing the metrics.
    """
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()

    all_conditions = tn + fp + fn + tp

    # Sensitivity
    tpr = tp / (tp + fn)

    # Specificity
    tnr = tn / (tn + fp)

    # Precision
    ppv = tp / (tp + fp)

    # Negative predictive value
    npv = tn / (tn + fn)

    # Miss rate
    fnr = fn / (fn + tp)

    # Fall out
    fpr = fp / (fp + tn)

    # False discovery rate
    fdr = fp / (fp + tp)

    # False omission rate
    false_omission_rate = fn / (fn + tn)

    # Prevalence threshold
    pt = np.sqrt(tpr * (1 - tnr) + tnr - 1) / (tpr + tnr - 1)

    # Thread score
    ts = tp / (tp + fn + fp)

    # Accuracy
    acc = (tp + tn) / all_conditions

    # Balanced accuracy
    ba = (tpr + tnr) / 2

    # F1 score
    # (harmonic mean of precision and sensitivity)
    f1 = 2 * tp / (2 * tp + fp + fn)

    # Matthews correlation coefficient
    mcc = ((tp * tn) - (fp * fn)) / np.sqrt(
        (tp + fp) * (tp + fn) * (tp + fp) * (tn + fn))

    # Fowlkes–Mallows index
    fm = np.sqrt(ppv * tpr)

    # Bookmaker informedness
    bm = tpr + tnr - 1

    # Markedness
    mk = ppv + npv - 1

    return {'condition_positive': tp + fn,
            'condition_negative': tn + fp,
            'true_positive': tp,
            'true_negative': tn,
            'false_positive': fp,
            'false_negative': fn,
            'sensitivity': tpr,
            'specificity': tnr,
            'precision': ppv,
            'negative_predictive_value': npv,
            'miss_rate': fnr,
            'fall_out': fpr,
            'false_discovery_rate': fdr,
            'false_omission_rate': false_omission_rate,
            'prevalence_threshold': pt,
            'thread_score': ts,
            'accuracy': acc,
            'balanced_accuracy': ba,
            'f1_score': f1,
            'matthews_correlation_coefficient': mcc,
            'fowlkes_mallows_index': fm,
            'bookmaker informedness': bm,
            'markedness': mk,
            }


In [5]:
# len(np.where(np.array(m7['labels_dev'][col[indexes_true]][2:].unstack().dropna() or m9['labels_dev'][col[indexes_true]][2:].unstack().dropna()) == False)[0])
# dev_t_8.mean()

# Combine the models outputs
dev_t_7_8 = np.logical_or(dev_t_7, dev_t_8) * 1
dev_7_8 = np.logical_and(dev_7, dev_8) * 1
dev_t_7_9 = np.logical_or(dev_t_7, dev_t_9) * 1
dev_7_9 = np.logical_and(dev_7, dev_9) * 1
dev_t_8_9 = np.logical_or(dev_t_8, dev_t_9) * 1
dev_8_9 = np.logical_and(dev_8, dev_9) * 1
dev_t_7_8_9 = np.logical_or(dev_t_7_8, dev_t_9) * 1
dev_7_8_9 = np.logical_and(dev_7_8, dev_9) * 1

train_t_7_8 = np.logical_or(train_t_7, train_t_8) * 1
train_7_8 = np.logical_and(train_7, train_8) * 1
train_t_7_9 = np.logical_or(train_t_7, train_t_9) * 1
train_7_9 = np.logical_and(train_7, train_9) * 1
train_t_8_9 = np.logical_or(train_t_8, train_t_9) * 1
train_8_9 = np.logical_and(train_8, train_9) * 1
train_t_7_8_9 = np.logical_or(train_t_7_8, train_t_9) * 1
train_7_8_9 = np.logical_and(train_7_8, train_9) * 1

(dev_7 & dev_8) == dev_7_8
# dev_7_8
# dev_7_8.shape == dev_t_7_8.shape

array([ True,  True,  True, ...,  True,  True,  True])

In [12]:
def pretty_metrics(y_pred, y_true):
    metrics = compute_metrics(y_pred, y_true)
    print('Sensitivity:', (metrics['sensitivity'] * 100).round(3))
    print('Specificity:', (metrics['specificity'] * 100).round(3))
    print('F1 score:', (metrics['f1_score'] * 100).round(3))

In [13]:
# Compute the metrics
# Metrics 7
print('model_7, dev')
pretty_metrics(dev_7, dev_t_7)
print('model_7, train')
pretty_metrics(train_7, train_t_7)
print()

# Metrics 8
print('model_8, dev')
pretty_metrics(dev_8, dev_t_8)
print('model_8, train')
pretty_metrics(train_8, train_t_8)
print()

# Metrics 9
print('model_9, dev')
pretty_metrics(dev_9, dev_t_9)
print('model_9, train')
pretty_metrics(train_9, train_t_9)
print()

# Metrics 7_8
print('model_7_8, dev')
pretty_metrics(dev_7_8, dev_t_7_8)
print('model_7_8, train')
pretty_metrics(train_7_8, train_t_7_8)
print()

# Metrics 7_9
print('model_7_9, dev')
pretty_metrics(dev_7_9, dev_t_7_9)
print('model_7_9, train')
pretty_metrics(train_7_9, train_t_7_9)
print()

# Metrics 8_9
print('model_8_9, dev')
pretty_metrics(dev_8_9, dev_t_8_9)
print('model_8_9, train')
pretty_metrics(train_8_9, train_t_8_9)
print()

# Metrics 7_8_9
print('model_7_8_9, dev')
pretty_metrics(dev_7_8_9, dev_t_7_8_9)
print('model_7_8_9, train')
pretty_metrics(train_7_8_9, train_t_7_8_9)
print()

model_7, dev
<ipython-input-4-4a7a02168cb1>:45: RuntimeWarning: invalid value encountered in sqrt
  pt = np.sqrt(tpr * (1 - tnr) + tnr - 1) / (tpr + tnr - 1)
<ipython-input-4-4a7a02168cb1>:62: RuntimeWarning: overflow encountered in longlong_scalars
  (tp + fp) * (tp + fn) * (tp + fp) * (tn + fn))
<ipython-input-4-4a7a02168cb1>:61: RuntimeWarning: invalid value encountered in sqrt
  mcc = ((tp * tn) - (fp * fn)) / np.sqrt(
Sensitivity: 41.515
Specificity: 86.972
F1 score: 31.401
model_7, train
Sensitivity: 56.342
Specificity: 91.137
F1 score: 37.581

model_8, dev
Sensitivity: 50.649
Specificity: 77.936
F1 score: 28.234
model_8, train
Sensitivity: 61.617
Specificity: 87.559
F1 score: 33.944

model_9, dev
Sensitivity: 50.77
Specificity: 84.12
F1 score: 33.782
model_9, train
Sensitivity: 61.376
Specificity: 89.609
F1 score: 37.241

model_7_8, dev
Sensitivity: 30.494
Specificity: 92.441
F1 score: 30.223
model_7_8, train
Sensitivity: 49.75
Specificity: 95.267
F1 score: 43.954

model_7_9, de

In [8]:
print('model_7, dev')
compute_metrics(dev_7, dev_t_7)
# print('model_7, train')
# compute_metrics(train_7, train_t_7)

model_7, dev
<ipython-input-4-4a7a02168cb1>:45: RuntimeWarning: invalid value encountered in sqrt
  pt = np.sqrt(tpr * (1 - tnr) + tnr - 1) / (tpr + tnr - 1)
<ipython-input-4-4a7a02168cb1>:62: RuntimeWarning: overflow encountered in longlong_scalars
  (tp + fp) * (tp + fn) * (tp + fp) * (tn + fn))
<ipython-input-4-4a7a02168cb1>:61: RuntimeWarning: invalid value encountered in sqrt
  mcc = ((tp * tn) - (fp * fn)) / np.sqrt(


{'condition_positive': 56185,
 'condition_negative': 530008,
 'true_positive': 23325,
 'true_negative': 460956,
 'false_positive': 69052,
 'false_negative': 32860,
 'sensitivity': 0.41514639138560117,
 'specificity': 0.8697151741105794,
 'precision': 0.2524979161479589,
 'negative_predictive_value': 0.9334569961281125,
 'miss_rate': 0.5848536086143988,
 'fall_out': 0.13028482588942053,
 'false_discovery_rate': 0.7475020838520411,
 'false_omission_rate': 0.06654300387188751,
 'prevalence_threshold': nan,
 'thread_score': 0.1862468759232495,
 'accuracy': 0.8261459962845001,
 'balanced_accuracy': 0.6424307827480903,
 'f1_score': 0.31401031219288916,
 'matthews_correlation_coefficient': nan,
 'fowlkes_mallows_index': 0.3237647274197874,
 'bookmaker informedness': 0.2848615654961806,
 'markedness': 0.1859549122760713}

In [9]:
# m7['labels_dev'][col[indexes_true]][2:].unstack().dropna()[58:60]
# m9['labels_dev'][col[indexes_true]][2:].unstack().dropna()[58:60]

A = np.array([0, 1, 0, 1])
B = np.array([0, 0, 1, 1])
print('A:')
print(A)
print('B:')
print(B)
print('Logic "and"')
print(np.logical_and(A, B) * 1)
print('Logic "or"')
print(np.logical_or(A, B) * 1)

A:
[0 1 0 1]
B:
[0 0 1 1]
Logic "and"
[0 0 0 1]
Logic "or"
[0 1 1 1]


In [66]:
# os.listdir('models_importances')
features_importances = pd.read_excel(os.path.join('models_importances', 'model_10_model.xlsx'))
features_names = features_importances['Feature name']
importances = features_importances['Importance']

feat_imp = [(name, importance) for name, importance in zip(features_names, importances)]

feat_imp_motg = [(name[name.rfind('(') + 1:-1], imp) for name, imp in feat_imp]
feat_imp_feat = [(name[:name.rfind('(') - 1], imp) for name, imp in feat_imp]
features = {name : 0 for name, _ in feat_imp_feat}
montages = {name : 0 for name, _ in feat_imp_motg}

for m in montages:
    imp_cum = [imp for name, imp in feat_imp_motg if name == m]
    # print(m, ':{0}'.format(sum(imp_cum)))
    montages[m] = sum(imp_cum)

montages = dict(sorted(montages.items(), key=lambda item: item[1], reverse=True))

for f in features:
    imp_cum = [imp for name, imp in feat_imp_feat if name == f]
    # print(m, ':{0}'.format(sum(imp_cum)))
    features[f] = sum(imp_cum)

features = dict(sorted(features.items(), key=lambda item: item[1], reverse=True))

features
montages

{'C3-P3': 0.16892702927000006,
 'F3-C3': 0.135145457296,
 'F8-T4': 0.07383746071399999,
 'C3-CZ': 0.0604306618,
 'C4-P4': 0.049072349174999995,
 'F7-T3': 0.04762200997259999,
 'T4-T6': 0.04534916372699999,
 'A1-T3': 0.04091016091299999,
 'P3-O1': 0.04069836271399999,
 'T4-A2': 0.03899627208099998,
 'FP1-F3': 0.038236074435999995,
 'FP2-F8': 0.0337982957,
 'T3-T5': 0.03292207497199999,
 'FP1-F7': 0.03198414448100001,
 'CZ-C4': 0.031294907675000004,
 'T6-O2': 0.027204526210000003,
 'F4-C4': 0.0266546653035,
 'T3-C3': 0.025462257100200007,
 'T5-O1': 0.016537690127999997,
 'P4-O2': 0.015007840980000001,
 'FP2-F4': 0.012027580311000005,
 'C4-T4': 0.007881048715899999}

In [68]:
# os.listdir('models_importances')
features_importances = pd.read_excel(os.path.join('models_importances', 'model_11_model.xlsx'))
features_names = features_importances['Feature name']
importances = features_importances['Importance']

feat_imp = [(name, importance) for name, importance in zip(features_names, importances)]

feat_imp_motg = [(name[name.rfind('(') + 1:-1], imp) for name, imp in feat_imp]
feat_imp_feat = [(name[:name.rfind('(') - 1], imp) for name, imp in feat_imp]
features = {name : 0 for name, _ in feat_imp_feat}
montages = {name : 0 for name, _ in feat_imp_motg}

for m in montages:
    imp_cum = [imp for name, imp in feat_imp_motg if name == m]
    # print(m, ':{0}'.format(sum(imp_cum)))
    montages[m] = sum(imp_cum)

montages = dict(sorted(montages.items(), key=lambda item: item[1], reverse=True))

for f in features:
    imp_cum = [imp for name, imp in feat_imp_feat if name == f]
    # print(m, ':{0}'.format(sum(imp_cum)))
    features[f] = sum(imp_cum)

features = dict(sorted(features.items(), key=lambda item: item[1], reverse=True))

features

{'MULTITAPER_GAMMA_30HZ_100HZ_POWER': 0.05652839324599999,
 'MULTITAPER_DELTA_05HZ_4HZ_POWER': 0.04686155951000001,
 'LINE_LENGTH': 0.041248758489999995,
 'POWER_RATIO_BETA_WAVE': 0.034037472259999986,
 'POWER_BETA_WAVE': 0.03265010041000001,
 'PETROSIAN_FRACTAL_DIMENSION': 0.028958469975999997,
 'WELCH_EPILEPSY_0HZ_6HZ_POWER': 0.02728906298,
 'POWER_ALPHA_WAVE': 0.025248110199999993,
 'POWER_RATIO_THETA_WAVE': 0.020947508899999998,
 'HJORTH_MOBILITY': 0.020584927990000005,
 'MULTITAPER_TOTAL_POWER': 0.020525710035999997,
 'MULTITAPER_GAMMA_30HZ_100HZ_POWER_RATIO': 0.020024253529999998,
 'MULTITAPER_EPILEPSY_2HZ_4HZ_POWER': 0.01962794968,
 'HJORTH_ACTIVITY': 0.019478680460000005,
 'MULTITAPER_EPILEPSY_1HZ_5HZ_POWER': 0.019437986730000002,
 'MEAN': 0.019386659344000006,
 'SPECTRAL_FLATNESS': 0.018317389040000003,
 'WELCH_EPILEPSY_0HZ_6HZ_POWER_RATIO': 0.018277349465,
 'WELCH_EPILEPSY_1HZ_5HZ_POWER': 0.017845230280000002,
 'SPECTRAL_CENTROID': 0.017584453886000006,
 'MULTITAPER_BETA_12HZ

In [48]:
d = {'t':5}
print(d)
d.update({'t': d.get('t', 0) + 6})
print(d)

{'t': 5}
{'t': 11}
